# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eat Orgasm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'


  # Pods for Eat Orgasm

  target 'Eat OrgasmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Eat OrgasmUITests' do
    # Pods for testing
  end

end
